name: project-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'liberica'
          java-version: '20.0.1'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: '8.3'
          build-root-directory: 'app'

      - name: Build project
        run: ./gradlew build

      - name: Check codestyle
        run: ./gradlew checkstyleMain

      - name: Publish test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 06adae8f1f1db641ff1121b8eddd13dad70481989e3174349ba14495b91a0b3d
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco  
